routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes(['register' => false]);
Route::get('changepassword','Auth\ChangePasswordController@showChangePasswordForm')->name('changepassword');
Route::post('changepassword','Auth\ChangePasswordController@changePassword');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/zohoGrantToken', 'ZohoGrantToken@index')->name('zohoGrantToken');
Route::resource('recognised-match-products', 'RecognisedMatchProductController')->middleware('auth');
Route::resource('single-word-products', 'SingleWordProductController')->middleware('auth');
Route::resource('countries', 'CountryController')->middleware('auth');
Route::resource('states', 'StateController')->middleware('auth');
Route::resource('company-attributes', 'CompanyAttributeController')->middleware('auth');

app/SingleWordProduct.php
<?php

namespace SOSZohoXeroIntegration;

use Illuminate\Database\Eloquent\Model;

class SingleWordProduct extends Model
{
    protected $fillable = [
        'mapping_word',
        'zoho_product_id'
    ];
}

app/Http/Controllers/SingleWordProductController.php
<?php

namespace SOSZohoXeroIntegration\Http\Controllers;

use Illuminate\Http\Request;
use SOSZohoXeroIntegration\SingleWordProduct;

class SingleWordProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = SingleWordProduct::latest()->paginate(10);

        return view('single-word-products.index',compact('products'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('single-word-products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'mapping_word' => 'required',
            'zoho_product_id' => 'required'
        ]);

        $product = new SingleWordProduct([
            'mapping_word' => $request->get('mapping_word'),
            'zoho_product_id' => $request->get('zoho_product_id')
        ]);

        $product->save();
        return redirect('/single-word-products')->with('success', 'Mapping word is successfully created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = SingleWordProduct::find($id);

        return view('single-word-products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = SingleWordProduct::find($id);

        return view('single-word-products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'mapping_word' => 'required',
            'zoho_product_id' => 'required'
        ]);

        $product = SingleWordProduct::find($id);
        $product->mapping_word = $request->get('mapping_word');
        $product->zoho_product_id = $request->get('zoho_product_id');

        $product->save();
        return redirect('/single-word-products')->with('success', 'Mapping word has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = SingleWordProduct::find($id);
        $product->delete();

        return redirect('/single-word-products')->with('success', 'Mapping word has been deleted Successfully');
    }
}

resources/views/single-word-products/create.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card uper">
                    <div class="card-header">
                        <h2>Add Product for Single Word Mapping</h2>
                        <div class="pull-right">
                            <a class="btn btn-primary" href="{{ route('single-word-products.index') }}"><i class="fas fa-chevron-left"></i> Back</a>
                        </div>
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                            <strong>Whoops!</strong> There were some problems with your input.<br><br>
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br />
                        @endif
                        <form method="post" action="{{ route('single-word-products.store') }}">
                            @csrf
                            <div class="form-group">
                                <label for="mapping_word">Mapping Word:</label>
                                <input type="text" class="form-control" name="mapping_word" value="{{ old('mapping_word') }}"/>
                            </div>
                            <div class="form-group">
                                <label for="zoho_product_id">Zoho Product ID:</label>
                                <input type="text" class="form-control" name="zoho_product_id" value="{{ old('zoho_product_id') }}"/>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Add</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/single-word-products/edit.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card uper">
                    <div class="card-header card-header">
                        <h2>Edit Mapping Word</h2>
                        <div class="pull-right">
                            <a class="btn btn-primary" href="{{ route('single-word-products.index') }}"><i class="fas fa-chevron-left"></i> Back</a>
                        </div>
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br />
                        @endif
                        <form method="POST" action="{{ route('single-word-products.update', $product->id) }}">
                            @method('PUT')
                            @csrf
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="mapping_word"><strong>Mapping Word:</strong></label>
                                        <input type="text" name="mapping_word"  class="form-control" value="{{ old('mapping_word', $product->mapping_word) }}"/>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="zoho_product_id"><strong>Zoho Product ID:</strong></label>
                                        <input type="text"  name="zoho_product_id"  class="form-control" value="{{ old('zoho_product_id', $product->zoho_product_id) }}"/>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/single-word-products/index.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="uper">
                    @if(session()->get('success'))
                        <div class="alert alert-success">
                            {{ session()->get('success') }}
                        </div>
                        <br />
                    @endif
                    <h2>Single Word Product Mapping</h2>
                    <div class="pull-right">
                        <a class="btn btn-success" href="{{ route('single-word-products.create') }}"><i class="fas fa-plus-circle"></i> Add New Word Mapping</a>
                    </div>
                    <br>
                    <div class="table-responsive">
                        <table class="table table-hover table-light ">
                            <thead class="thead-dark">
                            <th>ID</th>
                            <th>Mapping Word</th>
                            <th>Zoho Product ID</th>
                            <th colspan="2">Action</th>
                            </thead>
                            <tbody>
                            @if (count($products) === 0)
                                <tr>
                                    <td colspan="4">
                                        <div class="alert alert-warning text-center" role="alert">
                                            No Records Available
                                        </div>
                                    </td>
                                </tr>
                            @endif
                            @foreach($products as $product)
                                <tr>
                                    <td>{{$product->id}}</td>
                                    <td>{{$product->mapping_word}}</td>
                                    <td>{{$product->zoho_product_id}}</td>
                                    <td>
                                        <form action="{{ route('single-word-products.destroy',$product->id) }}" method="POST">
                                            <a class="btn btn-info" href="{{ route('single-word-products.show',$product->id) }}"><i class="far fa-eye"></i></a>
                                            <a class="btn btn-primary" href="{{ route('single-word-products.edit',$product->id) }}"><i class="far fa-edit"></i></a>
                                            @csrf
                                            @method('DELETE')
                                            <button onclick="return confirm('Are you sure you want to delete this item?')" type="submit" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    {!! $products->links() !!}
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('home') }}"><i class="fas fa-home"></i> Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/single-word-products/show.blade.php
@extends('layouts.app')
@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card uper">
                    <div class="card-header">
                        <div class="pull-left">
                            <h2>Mapping Word Details</h2>
                        </div>
                        <div class="pull-right">
                            <a class="btn btn-primary" href="{{ route('single-word-products.index') }}"><i class="fas fa-chevron-left"></i> Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Mapping Word:</strong>
                                {{ $product->mapping_word }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Zoho Product ID:</strong>
                                {{ $product->zoho_product_id }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection