routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes(['register' => false]);
Route::get('changepassword','Auth\ChangePasswordController@showChangePasswordForm')->name('changepassword');
Route::post('changepassword','Auth\ChangePasswordController@changePassword');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/zohoGrantToken', 'ZohoGrantToken@index')->name('zohoGrantToken');
Route::resource('recognised-match-products', 'RecognisedMatchProductController')->middleware('auth');
Route::resource('single-word-products', 'SingleWordProductController')->middleware('auth');
Route::resource('countries', 'CountryController')->middleware('auth');
Route::resource('states', 'StateController')->middleware('auth');
Route::resource('company-attributes', 'CompanyAttributeController')->middleware('auth');

app/CompanyAttribute.php
<?php

namespace SOSZohoXeroIntegration;

use Illuminate\Database\Eloquent\Model;

class CompanyAttribute extends Model
{
    protected $fillable = [
        'keyword',
        'industry',
        'channel',
        'category',
    ];
}

app/Http/Controllers/CompanyAttributeController.php
<?php

namespace SOSZohoXeroIntegration\Http\Controllers;

use Illuminate\Http\Request;
use SOSZohoXeroIntegration\CompanyAttribute;

class CompanyAttributeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $attributes = CompanyAttribute::latest()->paginate(10);

        return view('company-attributes.index',compact('attributes'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('company-attributes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'keyword' => 'required',
            'industry' => 'required',
            'channel' => 'required',
            'category' => 'required'
        ]);

        $attribute = new CompanyAttribute([
            'keyword' => $request->get('keyword'),
            'industry' => $request->get('industry'),
            'channel' => $request->get('channel'),
            'category' => $request->get('category')
        ]);

        $attribute->save();
        return redirect('/company-attributes')->with('success', 'Company Attribute is added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $attribute = CompanyAttribute::find($id);

        return view('company-attributes.show', compact('attribute'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $attribute = CompanyAttribute::find($id);

        return view('company-attributes.edit', compact('attribute'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'keyword' => 'required',
            'industry' => 'required',
            'channel' => 'required',
            'category' => 'required'
        ]);

        $attribute = CompanyAttribute::find($id);
        $attribute->keyword = $request->get('keyword');
        $attribute->industry = $request->get('industry');
        $attribute->channel = $request->get('channel');
        $attribute->category = $request->get('category');

        $attribute->save();
        return redirect('/company-attributes')->with('success', 'Company Attribute has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $attribute = CompanyAttribute::find($id);
        $attribute->delete();

        return redirect('/company-attributes')->with('success', 'Company attribute has been deleted Successfully');
    }
}

resources/views/company-attributes/create.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card uper">
                    <div class="card-header">
                        <h2>Add Company Attribute</h2>
                        <div class="pull-right">
                            <a class="btn btn-primary" href="{{ route('company-attributes.index') }}"><i class="fas fa-chevron-left"></i> Back</a>
                        </div>
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                            <strong>Whoops!</strong> There were some problems with your input.<br><br>
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br />
                        @endif
                        <form method="post" action="{{ route('company-attributes.store') }}">
                            @csrf
                            <div class="form-group">
                                <label for="keyword">Keyword:</label>
                                <input type="text" class="form-control" name="keyword"  value="{{ old('keyword') }}"/>
                            </div>
                            <div class="form-group">
                                <label for="industry">Industry:</label>
                                <input type="text" class="form-control" name="industry" value="{{ old('industry') }}"/>
                            </div>
                            <div class="form-group">
                                <label for="channel">Channel:</label>
                                <input type="text" class="form-control" name="channel" value="{{ old('channel') }}"/>
                            </div>
                            <div class="form-group">
                                <label for="category">Category:</label>
                                <input type="text" class="form-control" name="category" value="{{ old('category') }}"/>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Add</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/company-attributes/edit.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card uper">
                    <div class="card-header card-header">
                        <h2>Edit Company Attribute</h2>
                        <div class="pull-right">
                            <a class="btn btn-primary" href="{{ route('company-attributes.index') }}"><i class="fas fa-chevron-left"></i> Back</a>
                        </div>
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br />
                        @endif
                        <form method="POST" action="{{ route('company-attributes.update', $attribute->id) }}">
                            @method('PUT')
                            @csrf
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="keyword"><strong>Keyowrd:</strong></label>
                                        <input type="text" name="keyword"  class="form-control" value="{{ old('keyword',  $attribute->keyword) }}"/>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="industry"><strong>Industry:</strong></label>
                                        <input type="text" class="form-control" name="industry" value="{{ old('industry', $attribute->industry) }}"/>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="channel"><strong>Channel:</strong></label>
                                        <input type="text" class="form-control" name="channel" value="{{  old('channel', $attribute->channel) }}"/>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="category"><strong>Category:</strong></label>
                                        <input type="text" class="form-control" name="category" value="{{  old('category', $attribute->category) }}"/>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/company-attributes/index.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="uper">
                    @if(session()->get('success'))
                        <div class="alert alert-success">
                            {{ session()->get('success') }}
                        </div>
                        <br />
                    @endif
                    <h2>Company Attributes</h2>
                    <div class="pull-right">
                        <a class="btn btn-success" href="{{ route('company-attributes.create') }}"><i class="fas fa-plus-circle"></i> Add New Company Attribute</a>
                    </div>
                    <br>
                    <div class="table-responsive">
                        <table class="table table-hover table-light ">
                            <thead class="thead-dark">
                            <th>ID</th>
                            <th>Keyword</th>
                            <th>Industry</th>
                            <th>Channel</th>
                            <th>Category</th>
                            <th colspan="2">Action</th>
                            </thead>
                            <tbody>
                            @if (count($attributes) === 0)
                                <tr>
                                    <td colspan="6">
                                        <div class="alert alert-warning text-center" role="alert">
                                            No Records Available
                                        </div>
                                    </td>
                                </tr>
                            @endif
                            @foreach($attributes as $attribute)
                                <tr>
                                    <td>{{$attribute->id}}</td>
                                    <td>{{$attribute->keyword}}</td>
                                    <td>{{$attribute->industry}}</td>
                                    <td>{{$attribute->channel}}</td>
                                    <td>{{$attribute->category}}</td>
                                    <td>
                                        <form action="{{ route('company-attributes.destroy',$attribute->id) }}" method="POST">
                                            <a class="btn btn-info" href="{{ route('company-attributes.show',$attribute->id) }}"><i class="far fa-eye"></i></a>
                                            <a class="btn btn-primary" href="{{ route('company-attributes.edit',$attribute->id) }}"><i class="far fa-edit"></i></a>
                                            @csrf
                                            @method('DELETE')
                                            <button onclick="return confirm('Are you sure you want to delete this item?')" type="submit" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    {!! $attributes->links() !!}
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('home') }}"><i class="fas fa-home"></i> Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/company-attributes/show.blade.php
@extends('layouts.app')
@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card uper">
                    <div class="card-header">
                        <div class="pull-left">
                            <h2>Company Attribute Details</h2>
                        </div>
                        <div class="pull-right">
                            <a class="btn btn-primary" href="{{ route('company-attributes.index') }}"><i class="fas fa-chevron-left"></i> Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Keyword:</strong>
                                {{ $attribute->keyword }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Industry:</strong>
                                {{ $attribute->industry }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Channel:</strong>
                                {{ $attribute->channel }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Category:</strong>
                                {{ $attribute->category }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection