routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes(['register' => false]);
Route::get('changepassword','Auth\ChangePasswordController@showChangePasswordForm')->name('changepassword');
Route::post('changepassword','Auth\ChangePasswordController@changePassword');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/zohoGrantToken', 'ZohoGrantToken@index')->name('zohoGrantToken');
Route::resource('recognised-match-products', 'RecognisedMatchProductController')->middleware('auth');
Route::resource('single-word-products', 'SingleWordProductController')->middleware('auth');
Route::resource('countries', 'CountryController')->middleware('auth');
Route::resource('states', 'StateController')->middleware('auth');
Route::resource('company-attributes', 'CompanyAttributeController')->middleware('auth');

app/State.php
<?php

namespace SOSZohoXeroIntegration;

use Illuminate\Database\Eloquent\Model;

class State extends Model
{
    protected $fillable = [
        'abbreviation',
        'state',
        'country'
    ];
}

app/Http/Controllers/StateController.php
<?php

namespace SOSZohoXeroIntegration\Http\Controllers;

use Illuminate\Http\Request;
use SOSZohoXeroIntegration\State;

class StateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $states = State::latest()->paginate(10);

        return view('states.index',compact('states'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('states.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'abbreviation' => 'required',
            'state' => 'required',
            'country' => 'required'
        ]);

        $country = new State([
            'abbreviation' => $request->get('abbreviation'),
            'state' => $request->get('state'),
            'country' => $request->get('country')
        ]);

        $country->save();
        return redirect('/states')->with('success', 'State Mapping is added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $state = State::find($id);

        return view('states.show', compact('state'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $state = State::find($id);

        return view('states.edit', compact('state'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'abbreviation' => 'required',
            'state' => 'required',
            'country' => 'required'
        ]);

        $state = State::find($id);
        $state->abbreviation = $request->get('abbreviation');
        $state->state = $request->get('state');
        $state->country = $request->get('country');

        $state->save();
        return redirect('/states')->with('success', 'State Mapping has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $state = State::find($id);
        $state->delete();

        return redirect('/states')->with('success', 'State mapping has been deleted Successfully');
    }
}

resources/views/states/create.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card uper">
                    <div class="card-header">
                        <h2>Add State</h2>
                        <div class="pull-right">
                            <a class="btn btn-primary" href="{{ route('states.index') }}"><i class="fas fa-chevron-left"></i> Back</a>
                        </div>
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                            <strong>Whoops!</strong> There were some problems with your input.<br><br>
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br />
                        @endif
                        <form method="post" action="{{ route('states.store') }}">
                            @csrf
                            <div class="form-group">
                                <label for="abbreviation">Abbreviation:</label>
                                <input type="text" class="form-control" name="abbreviation" value="{{ old('abbreviation') }}"/>
                            </div>
                            <div class="form-group">
                                <label for="region">State:</label>
                                <input type="text" class="form-control" name="state" value="{{ old('state') }}"/>
                            </div>
                            <div class="form-group">
                                <label for="country">Country:</label>
                                <input type="text" class="form-control" name="country"  value="{{ old('country') }}"/>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Add</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/states/edit.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card uper">
                    <div class="card-header card-header">
                        <h2>Edit State Mapping</h2>
                        <div class="pull-right">
                            <a class="btn btn-primary" href="{{ route('states.index') }}"><i class="fas fa-chevron-left"></i> Back</a>
                        </div>
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br />
                        @endif
                        <form method="POST" action="{{ route('states.update', $state->id) }}">
                            @method('PUT')
                            @csrf
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="abbreviation"><strong>Abbreviation:</strong></label>
                                        <input type="text" class="form-control" name="abbreviation" value="{{ old('abbreviation', $state->abbreviation) }}"/>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="region"><strong>State:</strong></label>
                                        <input type="text" class="form-control" name="state" value="{{ old('state', $state->state) }}"/>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="country"><strong>Country:</strong></label>
                                        <input type="text" name="country"  class="form-control"value="{{ old('country', $state->country) }}"/>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/states/index.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
        td {
            vertical-align: middle;
        }
    </style>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="uper">
                    @if(session()->get('success'))
                        <div class="alert alert-success">
                            {{ session()->get('success') }}
                        </div>
                        <br />
                    @endif
                    <h2>States Mapping</h2>
                    <div class="pull-right">
                        <a class="btn btn-success" href="{{ route('states.create') }}"><i class="fas fa-plus-circle"></i> Add New State</a>
                    </div>
                    <br>
                    <div class="table-responsive">
                        <table class="table table-hover table-light ">
                            <thead class="thead-dark">
                            <th>ID</th>
                            <th>Abbreviation</th>
                            <th>State</th>
                            <th>Country</th>
                            <th colspan="2">Action</th>
                            </thead>
                            <tbody>
                            @if (count($states) === 0)
                                <tr>
                                    <td colspan="5">
                                        <div class="alert alert-warning text-center" role="alert">
                                            No Records Available
                                        </div>
                                    </td>
                                </tr>
                            @endif
                            @foreach($states as $state)
                                <tr>
                                    <td>{{$state->id}}</td>
                                    <td>{{$state->abbreviation}}</td>
                                    <td>{{$state->state}}</td>
                                    <td>{{$state->country}}</td>
                                    <td>
                                        <form action="{{ route('states.destroy',$state->id) }}" method="POST">
                                            <a class="btn btn-info" href="{{ route('states.show',$state->id) }}"><i class="far fa-eye"></i></a>
                                            <a class="btn btn-primary" href="{{ route('states.edit',$state->id) }}"><i class="far fa-edit"></i></a>
                                            @csrf
                                            @method('DELETE')
                                            <button onclick="return confirm('Are you sure you want to delete this item?')" type="submit" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    {!! $states->links() !!}
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('home') }}"><i class="fas fa-home"></i> Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/states/show.blade.php
@extends('layouts.app')
@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card uper">
                    <div class="card-header">
                        <div class="pull-left">
                            <h2>State Details</h2>
                        </div>
                        <div class="pull-right">
                            <a class="btn btn-primary" href="{{ route('states.index') }}"><i class="fas fa-chevron-left"></i> Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Abbreviation:</strong>
                                {{ $state->abbreviation }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>State:</strong>
                                {{ $state->state }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Country:</strong>
                                {{ $state->country }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection